name: BuildAll

#on: workflow_dispatch

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

#on:
#  push:
#    tags:
#      - '*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'
    - uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r26

    - uses: actions/checkout@v2
    
    - name: Get version
      uses: KageKirin/get-node-package-version@v0
      id: package_version
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'gradle'
        
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
        cache: 'yarn'
        
    - run: yarn
    - run: node update_version.js

    - name: get XMRig
      run: cd xmrig/lib-builder && mkdir build && mkdir build/src && mkdir build/build && make all && cd .. && cd .. 
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-xmrig
        path: |
          xmrig/lib-builder/script/build/src/xmrig/arm64-v8a/xmrig
          xmrig/lib-builder/script/build/src/xmrig/armeabi-v7a/xmrig
